export default {

	TOGGLE_LOADING: 'TOGGLE_LOADING',
	
	SELECT_MENU_ITEM: 'SELECT_MENU_ITEM',

	PROFILES_RECEIVED: 'PROFILES_RECEIVED',
	COURSES_RECEIVED: 'COURSES_RECEIVED',

	TUTORIALS_RECEIVED: 'TUTORIALS_RECEIVED',
	TUTORIAL_UPDATED: 'TUTORIAL_UPDATED',

	PROJECTS_RECEIVED: 'PROJECTS_RECEIVED',
	PROJECT_CREATED: 'PROJECT_CREATED',
	PROJECT_UPDATED: 'PROJECT_UPDATED',

	COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
	COMMENT_CREATED: 'COMMENT_CREATED',
	
	POSTS_RECEIVED: 'POSTS_RECEIVED',

	CURRENT_USER_RECIEVED: 'CURRENT_USER_RECIEVED',
	PROFILE_UPDDATED: 'PROFILE_UPDDATED'
}